### ISSUE TITLE
When there are no results allow for a illustration request

### ISSUE THREAD

**Issue by timmychatterbug** [chatterbugapp/design#2]
**CB Character App**: Chatterbug Library 
- [x] Make an illustration request when there is no search results 

Talk with @madebyelvis for more details

**Comment by madebyelvis** [comment]
<img width="1042" alt="button + txt" src="https://user-images.githubusercontent.com/31512813/86603429-46b48980-bfa4-11ea-85e6-2b5662147070.png">
![flow](https://user-images.githubusercontent.com/31512813/86603435-487e4d00-bfa4-11ea-94ff-a0fa216f439a.jpg)
